//
//  DXMTConfiguration.swift
//  WhiskyKit
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import os.log

/// Renders and places the per-bottle `dxmt.conf`.
///
/// DXMT reads its configuration from `DXMT_CONFIG_FILE`, falling back to
/// `dxmt.conf` in the process working directory, which for a Whisky launch is
/// the game's folder and never the bottle. So the file is written to the bottle
/// root and pointed at explicitly, the same way `dxvk.conf` is. DXMT opens the
/// file from its PE side, so the variable carries a `Z:` path.
public enum DXMTConfiguration {
    /// The file name inside the bottle.
    public static let fileName = "dxmt.conf"

    /// The range DXMT documents for `d3d11.metalSpatialUpscaleFactor`.
    public static let upscaleFactorRange: ClosedRange<Double> = 1.0 ... 2.0

    /// Where a bottle's generated config lives.
    public static func fileURL(bottleURL: URL) -> URL {
        bottleURL.appending(path: fileName)
    }

    /// Clamps an upscale factor into ``upscaleFactorRange``. NaN falls back to 2.0,
    /// DXMT's own default.
    public static func clampUpscaleFactor(_ value: Double) -> Double {
        guard value.isFinite else { return 2.0 }
        return min(max(value, upscaleFactorRange.lowerBound), upscaleFactorRange.upperBound)
    }

    /// The config file body for the given settings.
    ///
    /// Pure, so the UI can preview exactly what a launch will write.
    public static func render(
        frameRateLimit: Int,
        metalFXSpatial: Bool,
        upscaleFactor: Double,
        extraOptions: String
    ) -> String {
        var lines = [
            "# Generated by Whisky on every DXMT launch. Edit the bottle's DXMT",
            "# settings instead of this file; changes here are overwritten.",
            ""
        ]
        if frameRateLimit > 0 {
            lines.append("d3d11.preferredMaxFrameRate = \(frameRateLimit)")
        }
        if metalFXSpatial {
            let factor = clampUpscaleFactor(upscaleFactor)
            lines.append("d3d11.metalSpatialUpscaleFactor = \(String(format: "%.2f", factor))")
        }
        let extra = extraOptions
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        if !extra.isEmpty {
            lines.append("")
            lines.append("# Extra options from the bottle settings")
            lines.append(contentsOf: extra)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// The config file body for a bottle's settings.
    public static func render(settings: BottleSettings) -> String {
        render(
            frameRateLimit: settings.dxmtFrameRateLimit,
            metalFXSpatial: settings.dxmtMetalFXSpatial,
            upscaleFactor: settings.dxmtUpscaleFactor,
            extraOptions: settings.dxmtExtraOptions
        )
    }

    /// Writes the bottle's `dxmt.conf`, replacing any previous one.
    ///
    /// - Returns: The file's URL.
    @discardableResult
    public static func write(settings: BottleSettings, bottleURL: URL) throws -> URL {
        let url = fileURL(bottleURL: bottleURL)
        try Data(render(settings: settings).utf8).write(to: url, options: .atomic)
        return url
    }

    /// The environment DXMT tuning needs, as (key, value, reason).
    ///
    /// Every variable here is read only by DXMT, so exporting them on a launch
    /// that ends up on another backend is inert, the same reasoning that lets
    /// `DXVK_CONFIG_FILE` ride on every launch.
    public static func environment(
        settings: BottleSettings,
        bottleURL: URL,
        fileExists: (URL) -> Bool = { FileManager.default.fileExists(atPath: $0.path(percentEncoded: false)) }
    ) -> [LaunchEnvironmentEntry] {
        var result: [LaunchEnvironmentEntry] = []
        let conf = fileURL(bottleURL: bottleURL)
        if fileExists(conf) {
            result.append(LaunchEnvironmentEntry(
                "DXMT_CONFIG_FILE",
                GraphicsLogLocations.windowsPath(for: conf),
                reason: "Per-bottle dxmt.conf generated from the DXMT settings"
            ))
        }
        if settings.dxmtMetalFXSpatial {
            result.append(LaunchEnvironmentEntry(
                "DXMT_METALFX_SPATIAL_SWAPCHAIN",
                "1",
                reason: "DXMT MetalFX spatial upscaling enabled for this bottle"
            ))
        }
        return result
    }
}
